'use client'

import Image from 'next/image'
import Link from 'next/link'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import SoftwareTools from '@/components/sections/SoftwareTools'
import WhoWeServed from '@/components/service/WhoWeServed'
import FAQ from '@/components/sections/FAQ'
import ContactForm from '@/components/sections/ContactForm'
import RelatedServiceBlogs from '@/components/service/RelatedServiceBlogs'

const services = [
  { title: 'Power System Engineering for Extraction and Processing Facilities', image: '/images/industries/oil-gas-mining/contact-techs.png', desc: 'Oil, gas, and mining facilities require reliable power for critical equipment. Our studies support safe, continuous operation across complex industrial environments.', items: ['Electrical system design for industrial plants', 'Short circuit and protection studies', 'Motor starting analysis', 'Power system stability analysis', 'Electrical safety assessments'] },
  { title: 'Power System Reliability for Remote Operations', image: '/images/industries/oil-gas-mining/backup-batteries.webp', desc: 'Many energy extraction sites operate in isolated or weak-grid environments. Keentel Engineering evaluates resilient operating strategies for remote facilities.', items: ['Microgrid operation', 'Generator stability', 'Power quality performance', 'Backup generation reliability'] },
  { title: 'Electrical Safety and Hazardous Location Design', image: '/images/industries/oil-gas-mining/power-quality-harmonic.webp', desc: 'Oil and gas facilities must comply with strict electrical safety requirements. Our work supports compliance with NEC and international safety standards.', items: ['Hazardous area electrical design', 'Grounding system analysis', 'Protection system design', 'Arc flash hazard evaluation'] },
]

const faqs = [
  ['Why are electrical reliability studies important for mining operations?', 'Equipment downtime can result in major production losses.'],
  ['What is microgrid analysis?', 'It evaluates isolated power systems operating independently from the main grid.'],
  ['Why are motor starting studies important in oil and gas facilities?', 'Large motors can cause voltage dips during startup.'],
  ['What is hazardous area electrical design?', 'It ensures electrical equipment operates safely in explosive environments.'],
  ['What standards apply to these facilities?', 'NEC hazardous location codes, IEEE standards, and industry safety regulations.'],
] as const

export default function OilGasMiningPage() {
  return <><Header /><main className="overflow-x-clip bg-white">
    <section className="relative flex min-h-[calc(100svh-var(--site-header-height))] items-end overflow-hidden bg-[#050D31] pt-32 lg:items-center">
      <video src="/videos/Oil, Gas & Mining Operations.mov" autoPlay muted loop playsInline preload="metadata" className="absolute inset-0 h-full w-full object-cover" aria-label="Oil gas and mining power infrastructure" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,13,49,.97)_0%,rgba(5,13,49,.88)_43%,rgba(5,13,49,.25)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(5,13,49,.96)_0%,transparent_58%)] lg:hidden" /><div className="pointer-events-none absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.08)_1px,transparent_1px)] [background-size:72px_72px]" />
      <div className="relative z-10 mx-auto w-full max-w-7xl px-5 pb-16 sm:px-8 sm:pb-20 lg:px-10 lg:py-24"><div className="max-w-4xl"><div className="mb-6 flex items-center gap-3"><span className="h-px w-10 bg-[#EE58C4]" /><span className="font-jost text-xs font-bold uppercase tracking-[.22em] text-[#F38AD7]">Industries We Serve · Oil, Gas & Mining</span></div><h1 className="max-w-4xl font-urbanist text-4xl font-black leading-[1.03] tracking-[-.035em] text-white sm:text-5xl lg:text-[4.25rem]">Power system engineering for oil, gas and mining facilities.</h1><p className="mt-7 max-w-2xl font-jost text-base leading-7 text-white/75 sm:text-lg">Oil, gas, and mining operations often operate in remote locations where electrical reliability is critical for safe and continuous operations. These facilities rely on robust power systems to support drilling equipment, processing plants, pumps, and heavy industrial loads.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="https://calendly.com/keentel-engineering/15min" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-14 items-center justify-center rounded-full bg-gradient-to-r from-[#C82DA0] to-[#832478] px-7 font-jost text-sm font-bold text-white">Schedule a Consultation <span className="ml-2">→</span></a><a href="#operations-capabilities" className="inline-flex min-h-14 items-center justify-center rounded-full border border-white/25 bg-white/10 px-7 font-jost text-sm font-bold text-white backdrop-blur-sm">Explore capabilities</a></div></div><div className="mt-14 grid max-w-3xl grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/15 bg-white/15 sm:grid-cols-4">{[['Remote sites','Operating expertise'],['Microgrids','Reliability studies'],['NEC / IEEE','Safety alignment'],['24 / 7','Operational focus']].map(([v,l])=><div key={l} className="bg-[#07113D]/85 px-4 py-4 backdrop-blur-md sm:px-5"><p className="font-urbanist text-sm font-black text-white sm:text-base">{v}</p><p className="mt-1 font-jost text-[.65rem] uppercase tracking-wider text-white/50">{l}</p></div>)}</div></div>
    </section>
    <section className="py-20 sm:py-24 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[.75fr_1.25fr] lg:gap-20 lg:px-10"><div><p className="font-jost text-xs font-bold uppercase tracking-[.2em] text-[#A8228A]">Industrial operations partner</p><h2 className="mt-4 font-urbanist text-3xl font-black leading-tight text-[#06103C] sm:text-4xl">Reliable power for demanding and remote operations.</h2></div><div className="border-l-2 border-[#A8228A]/20 pl-6 sm:pl-9"><p className="font-jost text-lg leading-8 text-[#343B55]">Critical extraction and processing equipment depends on robust electrical infrastructure, stable generation, and coordinated protection.</p><p className="mt-5 font-jost leading-7 text-gray-600">Our engineers connect system design, operational reliability, hazardous-location requirements, and electrical safety into practical solutions for challenging facilities.</p></div></div></section>
    <section id="operations-capabilities" className="bg-[#F3F5FA] py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="mb-12 grid gap-5 lg:grid-cols-[1fr_.55fr] lg:items-end"><div><p className="font-jost text-xs font-bold uppercase tracking-[.2em] text-[#A8228A]">Operational capabilities</p><h2 className="mt-4 font-urbanist text-3xl font-black text-[#06103C] sm:text-4xl lg:text-5xl">Engineering for reliability, safety, and continuity.</h2></div><p className="max-w-lg font-jost leading-7 text-gray-600 lg:justify-self-end">Specialized support for industrial plants, weak-grid sites, microgrids, and hazardous operating environments.</p></div><div className="border-t-2 border-[#06103C]">{services.map((s,i)=><article key={s.title} className="grid gap-6 border-b border-[#BFC5D2] py-10 sm:py-14 lg:grid-cols-12 lg:items-center lg:gap-10 lg:py-16"><div className="flex items-center gap-4 lg:col-span-1 lg:block lg:self-start"><span className="font-urbanist text-4xl font-black text-[#A8228A]/20 sm:text-5xl">0{i+1}</span><span className="h-px flex-1 bg-[#A8228A]/30 lg:mt-5 lg:block lg:w-full" /></div><div className={`relative min-h-[250px] overflow-hidden sm:min-h-[360px] lg:col-span-5 lg:min-h-[390px] ${i%2===1?'lg:order-3':''}`}><Image src={s.image} alt={s.title} fill sizes="(max-width:1024px) 100vw,42vw" className="object-cover" /></div><div className={`lg:col-span-6 ${i%2===1?'lg:order-2 lg:pr-10':'lg:pl-6'}`}><p className="font-jost text-[.65rem] font-bold uppercase tracking-[.2em] text-[#A8228A]">Operations capability · 0{i+1}</p><h3 className="mt-3 font-urbanist text-2xl font-black leading-tight text-[#06103C] sm:text-3xl lg:text-4xl">{s.title}</h3><p className="mt-5 font-jost text-base leading-7 text-gray-600 sm:text-lg">{s.desc}</p><div className="mt-7 grid gap-x-7 gap-y-3 sm:grid-cols-2">{s.items.map(item=><div key={item} className="flex items-start gap-3 border-t border-[#CDD2DD] pt-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#A8228A]" /><span className="font-jost text-sm leading-5 text-[#343B55]">{item}</span></div>)}</div></div></article>)}</div></div></section>
    <SoftwareTools heading="Our Software Capabilities" /><ContactForm source="oil-gas-mining" /><WhoWeServed showHeading /><FAQ items={faqs.map(([q,a])=>({q,a}))} eyebrow="Oil, Gas & Mining FAQ" title={<>Frequently Asked<br />Questions</>} description="Straight answers about remote power reliability, motor starting, microgrids, and hazardous-location engineering." />
    <section className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-col items-start justify-between gap-7 rounded-[1.75rem] bg-[linear-gradient(115deg,#F6EAF3,#EEF1FA)] p-7 sm:p-10 lg:flex-row lg:items-center"><div><p className="font-jost text-xs font-bold uppercase tracking-[.2em] text-[#A8228A]">Keentel&apos;s Grid IQ</p><h2 className="mt-3 font-urbanist text-2xl font-black text-[#06103C] sm:text-3xl">Insight for demanding power systems.</h2><p className="mt-3 font-jost text-gray-600">Explore our latest insights on power system studies, protection engineering, and grid modeling.</p></div><Link href="/blog" className="inline-flex shrink-0 rounded-full bg-[#06103C] px-7 py-4 font-jost text-sm font-bold text-white">View All Articles →</Link></div></div></section>
    <RelatedServiceBlogs terms={['oil', 'gas', 'mining', 'industrial', 'motor', 'microgrid']} title="Oil, Gas & Mining Insights" />
  </main><Footer /></>
}
