'use client'

import Image from 'next/image'
import Link from 'next/link'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import SoftwareTools from '@/components/sections/SoftwareTools'
import WhoWeServed from '@/components/service/WhoWeServed'
import FAQ from '@/components/sections/FAQ'
import ContactForm from '@/components/sections/ContactForm'
import RelatedServiceBlogs from '@/components/service/RelatedServiceBlogs'

const studies = [
  { title: 'Transmission Planning', desc: 'Support grid expansion through power flow, contingency, and stability studies to identify constraints and improve system reliability.' },
  { title: 'Load Flow Analysis', desc: 'Evaluate voltage stability, load distribution, and losses to ensure efficient power performance during normal and peak demand.' },
  { title: 'Short Circuit Studies', desc: 'Determine fault current levels, validate equipment ratings, and verify protection devices operate correctly during abnormal system events.' },
  { title: 'Protective Coordination', desc: 'Optimize relay and breaker settings using time-current analysis to isolate faults quickly and minimize system disruption.' },
  { title: 'Harmonic Analysis', desc: 'Detect waveform distortion from inverter sources and nonlinear loads through harmonic analysis and mitigation studies.' },
  { title: 'Grounding Protection', desc: 'Reduce step and touch voltage risks through grounding studies, fault analysis, and protection performance evaluation.' },
]

const faqs = [
  ['Why are short circuit studies important for industrial plants?', 'They ensure electrical equipment can safely withstand fault currents and prevent catastrophic failure.'],
  ['What is arc flash analysis?', 'It evaluates energy released during an electrical arc fault to determine safety zones and PPE requirements.'],
  ['What causes harmonics in industrial systems?', 'Variable frequency drives, rectifiers, and other power electronic equipment can introduce harmonic distortion.'],
  ['What are NERC reliability standards?', 'NERC reliability standards ensure that only the faulted portion of the system is isolated, minimizing downtime.'],
  ['What industries require these studies?', 'Manufacturing, chemical processing, heavy industry, and industrial plants with complex electrical networks.'],
  ['How do load flow studies benefit industrial facilities?', 'They identify voltage drops, energy losses, and potential overloads before equipment failures occur.'],
  ['Can Keentel assist with renewable integration in industrial facilities?', 'Yes, we evaluate solar, wind, and storage integration to ensure stability and reliability.'],
] as const

export default function IndustrialPowerEngineeringPage() {
  return <><Header /><main className="overflow-x-clip bg-white">
    <section className="relative flex min-h-[780px] items-end overflow-hidden bg-[#050D31] pt-32 sm:min-h-[820px] lg:min-h-[760px] lg:items-center"><video autoPlay muted loop playsInline preload="metadata" className="absolute inset-0 h-full w-full object-cover"><source src="/videos/Industrial & Manufacturing Facilities.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,13,49,.97)_0%,rgba(5,13,49,.88)_43%,rgba(5,13,49,.25)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(5,13,49,.96)_0%,transparent_58%)] lg:hidden" /><div className="pointer-events-none absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.08)_1px,transparent_1px)] [background-size:72px_72px]" /><div className="relative z-10 mx-auto w-full max-w-7xl px-5 pb-16 sm:px-8 sm:pb-20 lg:px-10 lg:py-24"><div className="max-w-4xl"><div className="mb-6 flex items-center gap-3"><span className="h-px w-10 bg-[#EE58C4]" /><span className="font-jost text-xs font-bold uppercase tracking-[.22em] text-[#F38AD7]">Industries We Serve · Industrial Power</span></div><h1 className="font-urbanist text-4xl font-black leading-[1.03] tracking-[-.035em] text-white sm:text-5xl lg:text-[4.25rem]">Reliable power engineering for industrial electrical infrastructure.</h1><p className="mt-7 max-w-2xl font-jost text-base leading-7 text-white/75 sm:text-lg">Specialized electrical solutions for manufacturing and industrial facilities to ensure safe, efficient, and uninterrupted operations.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="https://calendly.com/keentel-engineering/15min" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-14 items-center justify-center rounded-full bg-gradient-to-r from-[#C82DA0] to-[#832478] px-7 font-jost text-sm font-bold text-white">Schedule a Consultation <span className="ml-2">→</span></a><a href="#industrial-studies" className="inline-flex min-h-14 items-center justify-center rounded-full border border-white/25 bg-white/10 px-7 font-jost text-sm font-bold text-white">Explore capabilities</a></div></div><div className="mt-14 grid max-w-3xl grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/15 bg-white/15 sm:grid-cols-4">{[['HV / MV','System expertise'],['IEEE / NFPA','Safety alignment'],['24 / 7','Operations focus'],['Plant-ready','Engineering output']].map(([v,l])=><div key={l} className="bg-[#07113D]/85 px-4 py-4"><p className="font-urbanist text-sm font-black text-white sm:text-base">{v}</p><p className="mt-1 font-jost text-[.65rem] uppercase tracking-wider text-white/50">{l}</p></div>)}</div></div></section>
    <section className="py-20 sm:py-24 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[.75fr_1.25fr] lg:gap-20 lg:px-10"><div><p className="font-jost text-xs font-bold uppercase tracking-[.2em] text-[#A8228A]">Industrial engineering partner</p><h2 className="mt-4 font-urbanist text-3xl font-black leading-tight text-[#06103C] sm:text-4xl">Safe, efficient systems for complex industrial loads.</h2></div><div className="border-l-2 border-[#A8228A]/20 pl-6 sm:pl-9"><p className="font-jost text-lg leading-8 text-[#343B55]">At Keentel Engineering, we provide specialized electrical engineering services tailored to industrial plants, manufacturing facilities, and processing operations.</p><p className="mt-5 font-jost leading-7 text-gray-600">Our solutions help clients design safe, efficient, and compliant electrical systems, reduce downtime, and improve operational performance.</p></div></div></section>
    <section id="industrial-studies" className="bg-[#06103C] py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-16"><div className="lg:sticky lg:top-28 lg:self-start"><p className="font-jost text-xs font-bold uppercase tracking-[.2em] text-[#F075D2]">Industrial studies</p><h2 className="mt-4 font-urbanist text-3xl font-black leading-tight text-white sm:text-4xl">Analysis that protects uptime, equipment, and people.</h2><p className="mt-5 font-jost leading-7 text-white/60">Industrial electrical systems often involve complex distribution networks, multiple substations, and high-demand processes.</p><div className="relative mt-8 min-h-[270px] overflow-hidden sm:min-h-[360px]"><Image src="/images/industries/industrial-power-engineering/electrical-system-design.webp" alt="Industrial electrical system design" fill sizes="(max-width:1024px) 100vw,40vw" className="object-cover" /></div></div><div className="border-t border-white/20">{studies.map((study,i)=><article key={study.title} className="grid gap-4 border-b border-white/15 py-7 sm:grid-cols-[4rem_1fr] sm:py-9"><span className="font-urbanist text-xl font-black text-[#F075D2]/45">0{i+1}</span><div><h3 className="font-urbanist text-xl font-black text-white sm:text-2xl">{study.title}</h3><p className="mt-3 font-jost leading-7 text-white/60">{study.desc}</p><Link href="/service/power-system-studies" className="mt-4 inline-flex font-jost text-sm font-bold text-[#F075D2]">Explore this study →</Link></div></article>)}</div></div></div></section>
    <section className="py-20 sm:py-24 lg:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:gap-20 lg:px-10"><div><p className="font-jost text-xs font-bold uppercase tracking-[.2em] text-[#A8228A]">System design</p><h2 className="mt-4 font-urbanist text-3xl font-black text-[#06103C] sm:text-4xl">Electrical System Design and Optimization</h2><p className="mt-6 font-jost text-lg leading-8 text-[#343B55]">Efficient power distribution is critical to operational success in industrial environments.</p><div className="mt-7 space-y-5"><div className="border-t border-[#CDD2DD] pt-4"><h3 className="font-urbanist font-bold text-[#06103C]">Electrical Distribution System Design</h3><p className="mt-2 font-jost text-gray-600">Designing main and secondary feeders, bus configurations, and redundancy.</p></div><div className="border-t border-[#CDD2DD] pt-4"><h3 className="font-urbanist font-bold text-[#06103C]">Switchgear and Breaker Specification</h3><p className="mt-2 font-jost text-gray-600">Selecting equipment rated for load, fault current, and plant safety requirements.</p></div></div></div><div className="relative min-h-[350px] overflow-hidden sm:min-h-[480px]"><Image src="/images/industries/industrial-power-engineering/contact-techs.png" alt="Industrial electrical engineering team" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover" /></div></div></section>
    <SoftwareTools heading="Our Software Capabilities" /><ContactForm source="industrial-power-engineering" /><WhoWeServed showHeading /><FAQ items={faqs.map(([q,a])=>({q,a}))} eyebrow="Industrial Power FAQ" title={<>Frequently Asked<br />Questions</>} description="Straight answers about industrial studies, arc flash, harmonics, protection, and electrical reliability." />
    <section className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-col items-start justify-between gap-7 rounded-[1.75rem] bg-[linear-gradient(115deg,#F6EAF3,#EEF1FA)] p-7 sm:p-10 lg:flex-row lg:items-center"><div><p className="font-jost text-xs font-bold uppercase tracking-[.2em] text-[#A8228A]">Keentel&apos;s Grid IQ</p><h2 className="mt-3 font-urbanist text-2xl font-black text-[#06103C] sm:text-3xl">Insight for industrial power systems.</h2><p className="mt-3 font-jost text-gray-600">Explore our latest insights on power system studies, substation design, and industrial electrical engineering.</p></div><Link href="/blog" className="inline-flex shrink-0 rounded-full bg-[#06103C] px-7 py-4 font-jost text-sm font-bold text-white">View All Articles →</Link></div></div></section>
    <RelatedServiceBlogs terms={['industrial', 'power system', 'arc flash', 'motor', 'protection']} title="Industrial Power Insights" />
  </main><Footer /></>
}
